[2022-03-04 13:38:09,839] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2022-03-04 13:38:09,841] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2022-03-04 13:38:09,843] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2022-03-04 13:38:09,847] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2022-03-04 13:38:09,850] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2022-03-04 13:38:09,854] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2022-03-04 13:38:09,856] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2022-03-04 13:38:09,860] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2022-03-04 13:38:09,864] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2022-03-04 13:38:21,182] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2022-03-04 13:38:21,199] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2022-03-04 13:38:22,543] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2022-03-04 13:38:22,545] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2022-03-04 13:38:22,635] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2022-03-04 13:38:43,043] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2022-03-04 13:38:43,048] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2022-03-04 13:40:43,698] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2022-03-04 13:40:43,701] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2022-03-04 13:41:47,822] [WARNING] __main__ main.py:182 - closing all external connections
[2022-03-04 13:41:47,826] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2022-03-04 13:41:47,829] [WARNING] __main__ main.py:194 - asyncmain exiting
